#!/bin/bash
#
# Satellite-Hybrid Management System — headend sender installer
#
#   curl -fsSL https://raw.githubusercontent.com/caritechsolutions/Satellite-Hybrid-Management-System/main/install.sh | sudo bash
#
# Builds the bundled modified librist (VSF TR-06-4 Part 6/7), the marker tools,
# and deploys the web management interface.
#
# Re-runnable: pulls latest code, preserves channel config.
# Env: BRANCH=<branch>  PORT=<http port>  SKIP_LIBRIST=1
#
set -e

REPO="https://github.com/caritechsolutions/Satellite-Hybrid-Management-System.git"
BRANCH="${BRANCH:-main}"
APP_DIR="/opt/shms"
WEB_ROOT="${APP_DIR}/rist-monitor"
SITE_NAME="rist-monitor"
LOG_DIR="/var/log/rist-monitor"
PORT="${PORT:-80}"

# Files that hold runtime state and must survive a code update
# part8-monitor/config/instances.json is gitignored and so survives the
# reset --hard on a re-run, but it is listed explicitly anyway: the fresh-install
# path does rm -rf on APP_DIR, and relying on "untracked files happen to
# survive" is the kind of assumption that holds until someone adds a git clean.
STATE_FILES="rist-monitor/config/transports.json rist-monitor/config/channels.json rist-monitor/config/satellites.json rist-monitor/data/receivers.json part8-monitor/config/instances.json"

say()  { printf '\n\033[1;36m==> %s\033[0m\n' "$*"; }
info() { printf '    %s\n' "$*"; }
warn() { printf '\033[1;33m    WARNING: %s\033[0m\n' "$*"; }
die()  { printf '\033[1;31m    ERROR: %s\033[0m\n' "$*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "run as root (use sudo)"

say "Satellite-Hybrid Management System — installer"
info "branch : ${BRANCH}"
info "target : ${APP_DIR}"

# ---------------------------------------------------------------- packages
say "Installing packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq \
    nginx git curl ca-certificates \
    php-fpm php-cli php-curl php-mbstring php-xml \
    gcc g++ meson ninja-build pkg-config \
    libmbedtls-dev libcjson-dev libmicrohttpd-dev \
    ffmpeg >/dev/null
info "web stack + build toolchain + ffmpeg installed"

PHP_VER="$(ls /etc/php 2>/dev/null | sort -V | tail -1)"
[ -n "$PHP_VER" ] || die "no PHP found under /etc/php"
PHP_SOCK="/run/php/php${PHP_VER}-fpm.sock"
info "php    : ${PHP_VER} (${PHP_SOCK})"

DISABLED="$(php -r 'echo ini_get("disable_functions");' 2>/dev/null || true)"
case "$DISABLED" in
    *proc_open*|*exec*) warn "php disable_functions blocks proc_open/exec — channels will not start" ;;
esac

# ---------------------------------------------------------------- code
say "Fetching application code"
# Older installs chowned the whole tree (including .git) to www-data, which
# makes root's git refuse with "dubious ownership". Whitelist system-wide:
# --system writes /etc/gitconfig, so it does not depend on $HOME being set
# (which it is not, reliably, under `curl | sudo bash`).
if ! git config --system --get-all safe.directory 2>/dev/null | grep -qx "$APP_DIR"; then
    git config --system --add safe.directory "$APP_DIR" \
        || warn "could not add safe.directory exception"
fi

BACKUP="$(mktemp -d)"
if [ -d "${APP_DIR}/.git" ]; then
    for f in $STATE_FILES; do
        if [ -f "${APP_DIR}/${f}" ]; then
            mkdir -p "${BACKUP}/$(dirname "$f")"
            cp "${APP_DIR}/${f}" "${BACKUP}/${f}"
        fi
    done
    info "preserved existing config"
    git -C "$APP_DIR" fetch --quiet origin "$BRANCH"
    git -C "$APP_DIR" reset --hard --quiet "origin/${BRANCH}"
    git -C "$APP_DIR" checkout --quiet -B "$BRANCH" "origin/${BRANCH}"
else
    rm -rf "$APP_DIR"
    git clone --quiet --branch "$BRANCH" "$REPO" "$APP_DIR"
fi
info "at $(git -C "$APP_DIR" rev-parse --short HEAD)"

for f in $STATE_FILES; do
    [ -f "${BACKUP}/${f}" ] && cp "${BACKUP}/${f}" "${APP_DIR}/${f}"
done
rm -rf "$BACKUP"

[ -d "$WEB_ROOT" ] || die "expected ${WEB_ROOT} — wrong branch?"

# ---------------------------------------------------------------- librist
if [ "${SKIP_LIBRIST:-0}" = "1" ]; then
    say "Skipping librist build (SKIP_LIBRIST=1)"
elif [ ! -d "${APP_DIR}/librist" ]; then
    warn "librist/ not in the repo — skipping build"
else
    # ------------------------------------------------ riststb sync check
    # librist is a modified fork shared with the box tree (riststb). The two
    # copies must agree on the files the Part 8 work touches, or the box and
    # the headend cut, number and filter the stream differently — which is a
    # protocol mismatch, not a build warning.
    #
    # riststb is not reachable from here, so the expected values are recorded
    # in librist/RISTSTB-SYNC, regenerated by ./librist-sync-update.sh on a
    # machine that has both trees. This checks the copy about to be built
    # against that record.
    #
    # Escape hatch: SKIP_LIBRIST_SYNC_CHECK=1
    SYNC_MANIFEST="${APP_DIR}/librist/RISTSTB-SYNC"
    if [ "${SKIP_LIBRIST_SYNC_CHECK:-0}" = "1" ]; then
        warn "librist/riststb sync check skipped (SKIP_LIBRIST_SYNC_CHECK=1)"
    elif [ ! -f "$SYNC_MANIFEST" ]; then
        warn "no librist/RISTSTB-SYNC in this checkout — sync unverified"
    elif ! command -v sha256sum >/dev/null 2>&1; then
        warn "sha256sum not available — librist sync unverified"
    else
        say "Checking librist against riststb"
        sync_bad=0
        sync_ref=$(awk '$1=="riststb"{print $2}' "$SYNC_MANIFEST")
        info "manifest claims riststb ${sync_ref:0:12}"

        # Tab-separated so literals may contain spaces. IFS is set per-read.
        while IFS=$'\t' read -r kind a b; do
            case "$kind" in
            sha256)
                # a = expected hex, b = path relative to librist/
                if [ ! -f "${APP_DIR}/librist/${b}" ]; then
                    warn "MISSING: librist/${b}"
                    sync_bad=1
                elif [ "$(sha256sum "${APP_DIR}/librist/${b}" | cut -d' ' -f1)" != "$a" ]; then
                    warn "CHANGED: librist/${b} does not match riststb"
                    sync_bad=1
                fi
                ;;
            require)
                # a = path, b = literal that must be present
                if ! grep -qF -- "$b" "${APP_DIR}/librist/${a}" 2>/dev/null; then
                    warn "MISSING from librist/${a}: ${b}"
                    sync_bad=1
                fi
                ;;
            forbid)
                if grep -qF -- "$b" "${APP_DIR}/librist/${a}" 2>/dev/null; then
                    warn "PRESENT in librist/${a} but must not be: ${b}"
                    sync_bad=1
                fi
                ;;
            esac
        done < <(grep -v '^[[:space:]]*#' "$SYNC_MANIFEST" | grep -v '^[[:space:]]*$')

        if [ "$sync_bad" -ne 0 ]; then
            printf '\n' >&2
            printf '    This repo'"'"'s librist/ no longer matches the riststb commit it\n' >&2
            printf '    claims to match (%s).\n\n' "${sync_ref:0:12}" >&2
            printf '    The box and the headend must run the SAME librist on the files\n' >&2
            printf '    listed above. Building this one would put a different packetiser,\n' >&2
            printf '    filter or sequence rule on the headend than the box runs.\n\n' >&2
            printf '    Fix the divergence in both trees, then regenerate the record:\n' >&2
            printf '        ./librist-sync-update.sh /path/to/riststb\n\n' >&2
            printf '    To build anyway (you are on your own): SKIP_LIBRIST_SYNC_CHECK=1\n' >&2
            die "librist diverged from riststb — refusing to build"
        fi
        info "librist matches riststb ${sync_ref:0:12}"
    fi

    say "Building bundled librist (Part 6/7 modified)"
    cd "${APP_DIR}/librist"
    rm -rf build
    meson setup build \
        --prefix=/usr/local \
        --buildtype=release \
        -Dbuiltin_cjson=false \
        -Dtest=false >/dev/null
    ninja -C build >/dev/null
    ninja -C build install >/dev/null
    ldconfig
    [ -x /usr/local/bin/ristsender ] || die "ristsender missing after build"
    info "librist installed to /usr/local"
    info "ristsender + ristreceiver in /usr/local/bin"
fi

# ---------------------------------------------------------------- tools
say "Building marker tools"
cd "$APP_DIR"
export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:/usr/local/lib64/pkgconfig:${PKG_CONFIG_PATH:-}"

build_tool() {
    src="$1"; out="$2"; libs="$3"
    if [ ! -f "$src" ]; then warn "${src} missing - skipped"; return; fi
    # shellcheck disable=SC2086
    if gcc -O2 -Wall -pthread -I/usr/local/include -o "/usr/local/bin/${out}" \
           "$src" -L/usr/local/lib $libs 2>"/tmp/${out}.err"; then
        chmod +x "/usr/local/bin/${out}"
        info "built ${out}"
    else
        warn "${out} failed to build - see /tmp/${out}.err"
    fi
}

# Headend: converts the weight-0 RIST peer back to TS with Part 7 markers
build_tool ristreceiver_with_markers.c ristreceiver_with_markers "-lrist -lpthread"

# Headend, PSI-excluded variant of the above. Same job, but non_null counts only
# the marker plus elementary streams -- PSI (0x0000-0x001F plus the PMT PID) is
# forwarded on the wire as before but left out of the count, because PSI is
# regenerated by the third-party mux and re-injected by the STB capture and so
# can never agree between the two ends. Named for where it runs and what it does;
# the legacy name above is kept in place and untouched.
build_tool headend_part7_sender.c      headend_part7_sender      "-lrist -lpthread"
build_tool rist_watchdog.c             rist_watchdog             ""
build_tool ristsender_marker.c         ristsender_marker         "-lrist -lpthread"

# Part 8 (out-of-band) recovery server. Separate binary on purpose: librist keeps
# FSR state in udp.c file-scope statics, so running this in its own process is
# what stops it disturbing the Part 6/7 units above. Ingests the full downlink
# multiplex and indexes PCR -> RTP sequence for PCR-addressed recovery.
build_tool part8_recovery_server.c     part8_recovery_server     "-lrist -lpthread -lm"

# STB-side Part 7 receiver: validates the markers headend_part7_sender inserts,
# counting elementary streams only and rebuilding each block to 35 packets. This
# runs on the BOX (ARM) -- built here only so a compile break is caught on the
# headend; the shipping binary comes from the ARM cross-build.
build_tool stb_part7_receiver.c        stb_part7_receiver        "-lrist -lpthread"

# ---------------------------------------------------------------- tsduck
# TSDuck is used to post-process the marked TS before the uplink: declare the
# marker PID in the PMT, and remap PIDs. Installed from a prebuilt .deb rather
# than built from source - no toolchain, no long compile.
say "Installing TSDuck"
if command -v tsp >/dev/null 2>&1 && tsp --version >/dev/null 2>&1; then
    info "already installed: $(tsp --version 2>&1 | head -1)"
else
    # A broken install (present but not runnable) is worse than none - clear it
    if command -v tsp >/dev/null 2>&1; then
        warn "tsp present but not running - purging before reinstall"
        dpkg --purge tsduck >/dev/null 2>&1 || true
    fi

    ARCH="$(dpkg --print-architecture)"
    . /etc/os-release
    info "host: ${ARCH} on ${PRETTY_NAME:-unknown}"

    # Ubuntu 24 packages use libssl3t64/libcurl4t64 and will NOT work on older releases
    case "${VERSION_CODENAME:-}" in
        noble|plucky|oracular) TSD_VER="3.43-4524"; TSD_TAG="ubuntu24" ;;
        jammy)                 TSD_VER="3.33-3139"; TSD_TAG="ubuntu22" ;;
        focal)                 TSD_VER="3.26-2349"; TSD_TAG="ubuntu20" ;;
        *) warn "unrecognised release - trying the ubuntu24 package"
           TSD_VER="3.43-4524"; TSD_TAG="ubuntu24" ;;
    esac

    TSD_DEB=""
    LOCAL_DEB="$(find "${APP_DIR}/packages" -name "tsduck*${TSD_TAG}*${ARCH}.deb" 2>/dev/null | head -1)"
    if [ -n "$LOCAL_DEB" ]; then
        info "using bundled package: $(basename "$LOCAL_DEB")"
        TSD_DEB="$LOCAL_DEB"
    else
        TSD_PKG="tsduck_${TSD_VER}.${TSD_TAG}_${ARCH}.deb"
        info "no bundled package for ${TSD_TAG}/${ARCH} - downloading ${TSD_VER}"
        TSD_DEB="/tmp/tsduck.deb"; rm -f "$TSD_DEB"
        for attempt in 1 2 3; do
            if curl -fsSL -o "$TSD_DEB" \
               "https://github.com/tsduck/tsduck/releases/download/v${TSD_VER}/${TSD_PKG}"; then
                break
            fi
            warn "download attempt ${attempt} failed"; sleep 2
        done
    fi

    if [ -s "$TSD_DEB" ]; then
        apt-get install -y -qq libcurl4 libpcsclite1 libedit2 >/dev/null 2>&1 || true
        dpkg -i "$TSD_DEB" >/dev/null 2>&1 || warn "dpkg reported issues - fixing dependencies"
        apt-get install -f -y -qq >/dev/null 2>&1 || true
        [ "$TSD_DEB" = "/tmp/tsduck.deb" ] && rm -f /tmp/tsduck.deb
    else
        warn "no TSDuck package available"
        warn "  download tsduck_${TSD_VER}.${TSD_TAG}_${ARCH}.deb from"
        warn "  https://github.com/tsduck/tsduck/releases and put it in ${APP_DIR}/packages/"
    fi

    if command -v tsp >/dev/null 2>&1 && tsp --version >/dev/null 2>&1; then
        info "installed: $(tsp --version 2>&1 | head -1)"
    else
        warn "TSDuck not available - PMT/PID post-processing will not run"
    fi
fi

# ---------------------------------------------------------------- dirs/perms
say "Setting up directories and permissions"
mkdir -p "${WEB_ROOT}/config" "${WEB_ROOT}/data" "$LOG_DIR"
touch "${LOG_DIR}/rist-monitor.log"

# The code stays root-owned so git never sees "dubious ownership" (and the
# web user cannot rewrite its own application). Only the state directories
# and the log are handed to www-data.
chown -R root:root "$APP_DIR"
find "$APP_DIR" -type d -exec chmod 755 {} \;
find "$APP_DIR" -type f -exec chmod 644 {} \;

chown -R www-data:www-data "${WEB_ROOT}/config" "${WEB_ROOT}/data" "$LOG_DIR"
chmod 775 "${WEB_ROOT}/config" "${WEB_ROOT}/data"
chmod 664 "${WEB_ROOT}"/config/*.json "${WEB_ROOT}"/data/*.json 2>/dev/null || true
chmod 775 "$LOG_DIR"; chmod 664 "${LOG_DIR}/rist-monitor.log"
info "code root-owned; config/, data/ and logs writable by www-data"

# The UI manages channels as systemd units. Rather than granting www-data a
# broad root cp/rm, a narrow helper installs only ristsender-*/ristmarker-* units.
say "Installing systemd unit helper"
cat > /usr/local/sbin/rist-unit <<'HELPER'
#!/bin/bash
# rist-unit - install/remove RIST channel systemd units (root helper for the web UI)
set -e
ACTION="$1"; NAME="$2"; SRC="$3"

case "$NAME" in
    ristsender-*|ristmarker-*) ;;
    *) echo "refusing unit name: $NAME" >&2; exit 1 ;;
esac
case "$NAME" in
    */*|*..*) echo "refusing path traversal: $NAME" >&2; exit 1 ;;
esac

DEST="/etc/systemd/system/${NAME}.service"
case "$ACTION" in
    install)
        [ -f "$SRC" ] || { echo "source not found: $SRC" >&2; exit 1; }
        install -m 0644 -o root -g root "$SRC" "$DEST"
        ;;
    remove)
        rm -f "$DEST"
        ;;
    *)
        echo "usage: rist-unit install|remove <unit-name> [source-file]" >&2; exit 1 ;;
esac
systemctl daemon-reload
HELPER
chmod 755 /usr/local/sbin/rist-unit
info "helper installed at /usr/local/sbin/rist-unit"

say "Granting systemd control to www-data"
cat > /etc/sudoers.d/rist-monitor <<'SUDO'
# Allow the web UI to manage RIST channel services only
www-data ALL=(root) NOPASSWD: /usr/local/sbin/rist-unit, /usr/bin/systemctl start ristsender-*, /usr/bin/systemctl stop ristsender-*, /usr/bin/systemctl restart ristsender-*, /usr/bin/systemctl enable ristsender-*, /usr/bin/systemctl disable ristsender-*, /usr/bin/systemctl is-active ristsender-*, /usr/bin/systemctl start ristmarker-*, /usr/bin/systemctl stop ristmarker-*, /usr/bin/systemctl restart ristmarker-*, /usr/bin/systemctl enable ristmarker-*, /usr/bin/systemctl disable ristmarker-*, /usr/bin/systemctl is-active ristmarker-*, /usr/bin/systemctl daemon-reload
SUDO
chmod 440 /etc/sudoers.d/rist-monitor
visudo -cf /etc/sudoers.d/rist-monitor >/dev/null || die "sudoers drop-in invalid"
info "www-data may manage ristsender-* / ristmarker-* units"

# ---------------------------------------------------------------- mcast bridge
# Internal multicast fabric: 238.0.0.0/8 routed to a member-less bridge, so a
# stream handed between local processes never touches a physical NIC. TSDuck's
# "-I ip" rejects a unicast address, so the internal hops need a real group.
say "Setting up the internal multicast bridge"
cat > /etc/systemd/system/rist-mcast-bridge.service <<'BRIDGE'
[Unit]
Description=Internal multicast bridge for RIST inter-process links
After=network-pre.target
Wants=network-pre.target
Before=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/bin/sh -c 'ip link show br-rist >/dev/null 2>&1 || ip link add name br-rist type bridge'
ExecStart=/bin/sh -c 'ip link set br-rist up'
ExecStart=/bin/sh -c 'ip link set br-rist multicast on'
ExecStart=/bin/sh -c 'ip addr show dev br-rist | grep -q "10.255.255.1/24" || ip addr add 10.255.255.1/24 dev br-rist'
ExecStart=/bin/sh -c 'ip route show 238.0.0.0/8 2>/dev/null | grep -q br-rist || ip route add 238.0.0.0/8 dev br-rist'
ExecStop=/bin/sh -c 'ip route del 238.0.0.0/8 dev br-rist 2>/dev/null || true'
ExecStop=/bin/sh -c 'ip link del br-rist 2>/dev/null || true'
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
BRIDGE
systemctl daemon-reload
systemctl enable --now rist-mcast-bridge >/dev/null 2>&1 || warn "bridge unit did not start"
if ip route show 238.0.0.0/8 2>/dev/null | grep -q br-rist; then
    info "br-rist up, 238.0.0.0/8 routed to it (reserved - do not use elsewhere)"
else
    warn "238.0.0.0/8 route not present - the tsp stage will not receive"
fi

# ------------------------------------------------------- Part 8 recovery server
# A NEW, SEPARATE sender. It must not perturb the Part 6/7 chains, so:
#
#   - the unit is named part8-recovery, which deliberately does NOT match the
#     ristsender-*/ristmarker-* prefixes the rist-unit helper and the www-data
#     sudoers drop-in accept. The web UI therefore cannot start, stop, enable or
#     replace it, by construction rather than by convention.
#   - it has its own listen port, its own debug socket under /run, and its own
#     journal identity. Nothing is shared with an existing unit.
#   - no existing unit file is written, and no existing unit's enable/disable
#     state is touched. Known oddities (the stale ristmarker-bbc reference, the
#     disabled ristsender-vacation) are left exactly as they are.
#
# Isolation is VERIFIED below, not asserted: unit state is captured before and
# after and the difference is printed.
say "Part 8 recovery servers (multi-instance)"

# One templated unit, one instance per transponder. Everything that could
# collide between instances is derived from %i: config file, debug socket,
# runtime and state directory, journal identity.
#
# ISOLATION FROM PART 7. The requirement is that the working Part 7 chains keep
# working, so:
#   - no existing unit file is written and no existing unit's enable state is
#     touched, here or by the UI;
#   - the existing SHMS UI and its sudoers drop-in are not modified. The Part 8
#     grant is a SEPARATE drop-in file and the Part 8 helper is a SEPARATE
#     script; rist-unit is neither widened nor reused;
#   - part8-unit never accepts a unit name. It takes an instance token, checks
#     it against ^[a-z0-9][a-z0-9-]{0,30}$, and CONSTRUCTS
#     part8-recovery@<token>.service itself, so no spelling of the argument can
#     reach a Part 7 unit;
#   - every create/remove/start/stop snapshots all rist* and part8* units before
#     and after and reports whether anything outside Part 8 changed. That report
#     is surfaced in the UI, not just logged.

P8_STATE_BEFORE="/tmp/part8-units-before.txt"
P8_STATE_AFTER="/tmp/part8-units-after.txt"
P8_PORT="${P8_PORT:-8801}"

capture_rist_state() {
    # EVERY service, not just rist*/part8*. rist-mcast-bridge.service already
    # showed that Part 7 does not all share one prefix; a pattern can only see
    # what was anticipated, so capture everything and classify afterwards.
    {
        systemctl list-units --type=service --all --plain --no-legend 2>/dev/null \
            | awk '{print "U", $1, $2, $3, $4}'
        systemctl list-unit-files --type=service --no-legend 2>/dev/null \
            | awk '{print "F", $1, $2}'
        for u in $(systemctl list-units --type=service --all --plain --no-legend 'rist*' 'part8*' 2>/dev/null | awk '{print $1}'); do
            printf 'P %s %s\n' "$u" "$(systemctl show -p MainPID --value "$u" 2>/dev/null)"
        done
    } 2>/dev/null | sort
}

capture_rist_state > "$P8_STATE_BEFORE"
info "captured pre-install unit state ($(wc -l < "$P8_STATE_BEFORE") lines)"

# --- receive buffer ceiling: CHECKED, NOT SET
# Deliberately not written and not applied. Raising net.core.rmem_max is a
# system-wide change to a running headend, and doing it as a side effect of an
# installer is the same class of surprise as the silent clamp it protects
# against. The default is 212992 -- about 28 ms of ingest at 59 Mb/s -- so a
# host that has not been raised WILL clamp, and this says so loudly with the
# command to fix it. Pass P8_SET_RMEM=1 to have the installer apply it.
P8_WANT_RMEM=33554432
P8_HAVE_RMEM="$(cat /proc/sys/net/core/rmem_max 2>/dev/null || echo 0)"
if [ "$P8_HAVE_RMEM" -ge "$P8_WANT_RMEM" ]; then
    info "net.core.rmem_max = ${P8_HAVE_RMEM} (adequate; SO_RCVBUF will not clamp)"
elif [ "${P8_SET_RMEM:-0}" = "1" ]; then
    printf 'net.core.rmem_max = %s\n' "$P8_WANT_RMEM" > /etc/sysctl.d/99-part8-recovery.conf
    sysctl -q -w net.core.rmem_max="$P8_WANT_RMEM" 2>/dev/null \
        || warn "could not apply rmem_max now"
    info "net.core.rmem_max raised to $(cat /proc/sys/net/core/rmem_max) (P8_SET_RMEM=1)"
else
    warn "net.core.rmem_max is ${P8_HAVE_RMEM}, below ${P8_WANT_RMEM}."
    warn "  Every instance's SO_RCVBUF request WILL be clamped and input will be"
    warn "  lost on burst. At 59 Mb/s ${P8_HAVE_RMEM} bytes is about $(( P8_HAVE_RMEM * 8 * 1000 / 59145890 )) ms of ingest."
    warn "  Fix, persistently:"
    warn "    echo 'net.core.rmem_max = ${P8_WANT_RMEM}' > /etc/sysctl.d/99-part8.conf"
    warn "    sysctl -w net.core.rmem_max=${P8_WANT_RMEM}"
    warn "  Each instance logs what it ACHIEVED at startup; check there, do not assume."
fi

# --- templated unit
if [ -f "${APP_DIR}/part8-recovery@.service" ]; then
    install -m 0644 -o root -g root "${APP_DIR}/part8-recovery@.service" \
        /etc/systemd/system/part8-recovery@.service
    info "installed part8-recovery@.service"
else
    warn "part8-recovery@.service missing from the repo"
fi
install -d -m 0755 /etc/part8/instances

# --- privilege path: SEPARATE helper, SEPARATE sudoers file
if [ -f "${APP_DIR}/part8-unit" ]; then
    install -m 0755 -o root -g root "${APP_DIR}/part8-unit" /usr/local/sbin/part8-unit
    info "helper at /usr/local/sbin/part8-unit (constructs part8-recovery@<token> itself)"
else
    warn "part8-unit missing from the repo"
fi

# A NEW drop-in. /etc/sudoers.d/rist-monitor is NOT read, edited or replaced.
cat > /etc/sudoers.d/part8-monitor <<'SUDO'
# Part 8 management UI. Deliberately a separate file from rist-monitor: the
# Part 7 grant is not widened, and this grant carries NO systemctl rights and NO
# wildcards. part8-unit builds the unit name from a validated instance token, so
# there is no argument that reaches a unit outside part8-recovery@.
www-data ALL=(root) NOPASSWD: /usr/local/sbin/part8-unit
SUDO
chmod 440 /etc/sudoers.d/part8-monitor
visudo -cf /etc/sudoers.d/part8-monitor >/dev/null || die "part8 sudoers drop-in invalid"
info "www-data may run part8-unit only (rist-monitor drop-in untouched)"

systemctl daemon-reload

# --- the management UI: its own nginx site file, its own port
P8_WEB="${APP_DIR}/part8-monitor"
if [ -d "$P8_WEB" ]; then
    install -d -m 0775 "${P8_WEB}/config"
    chown -R www-data:www-data "${P8_WEB}/config"

    # A NEW site file. The existing rist-monitor site is not read or modified.
    cat > /etc/nginx/sites-available/part8-monitor <<NGINX
server {
    listen ${P8_PORT};
    listen [::]:${P8_PORT};
    server_name _;
    root ${P8_WEB};
    index index.php;
    charset utf-8;

    access_log /var/log/nginx/part8-monitor.access.log;
    error_log  /var/log/nginx/part8-monitor.error.log;

    location / { try_files \$uri \$uri/ /index.php?\$query_string; }

    location ~ \.php\$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:${PHP_SOCK};
        fastcgi_read_timeout 60;
    }

    # No caching for the app's own assets. They are a few KB, and an operations
    # tool that keeps showing a stale panel after a deploy costs far more than
    # the bytes save. index.php also mtime-stamps the URLs, which is what makes
    # an already-cached copy get replaced.
    location /assets/ { add_header Cache-Control "no-cache, must-revalidate"; }
    location ~ ^/config/ { deny all; }
    location ~ /\.      { deny all; }

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";
}
NGINX
    ln -sf /etc/nginx/sites-available/part8-monitor /etc/nginx/sites-enabled/part8-monitor
    if nginx -t >/dev/null 2>&1; then
        systemctl reload nginx || warn "nginx reload failed"
        info "Part 8 UI on port ${P8_PORT}"
    else
        warn "nginx config test failed with the Part 8 site - removing it and reloading"
        rm -f /etc/nginx/sites-enabled/part8-monitor
        nginx -t >/dev/null 2>&1 && systemctl reload nginx || true
    fi
else
    warn "part8-monitor/ missing from the repo - UI not installed"
fi

# --- long-run observer (O1-O5), started by hand for a measurement run
if [ -f "${APP_DIR}/tests/part8/observe.py" ]; then
    install -m 0755 "${APP_DIR}/tests/part8/observe.py" /usr/local/bin/part8-observe
    install -d -m 0755 /var/log/part8-observe
    info "observer at /usr/local/bin/part8-observe"
    info "  run:  part8-observe --socket /run/part8-recovery/<instance>/debug.sock \\"
    info "                      --unit part8-recovery@<instance> --interval 30 &"
fi

# --- isolation check: what actually changed
capture_rist_state > "$P8_STATE_AFTER"
say "Isolation check: what changed in unit state"
if diff -u "$P8_STATE_BEFORE" "$P8_STATE_AFTER" > /tmp/part8-units-diff.txt 2>&1; then
    info "NOTHING changed at all"
else
    _changed="$(grep -E '^[+-][^+-]' /tmp/part8-units-diff.txt | grep -v 'part8' || true)"
    _rist="$(printf '%s\n' "$_changed" | grep -E 'rist' || true)"
    _other="$(printf '%s\n' "$_changed" | grep -vE 'rist' | grep -v '^$' || true)"
    if [ -n "$_rist" ]; then
        warn "A PART 7 UNIT CHANGED - this should not happen:"
        printf '%s\n' "$_rist" | sed 's/^/        /'
    else
        info "no rist* unit changed state, enablement or main PID"
    fi
    if [ -n "$_other" ]; then
        info "other units that moved during the install (informational):"
        printf '%s\n' "$_other" | head -12 | sed 's/^/        /'
    fi
    { grep -E '^\+[^+]' /tmp/part8-units-diff.txt | grep 'part8' || true; } | sed 's/^/        added: /'
    info "full diff: /tmp/part8-units-diff.txt"
fi
